site_name: django-pgschemas
site_url: https://django-pgschemas.readthedocs.io/
repo_url: https://github.com/lorinkoz/django-pgschemas
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
nav:
  - Intro: index.md
  - Multi-tenancy: overview.md
  - Usage: basic.md
  - Routing: routing.md
  - Advanced: advanced.md
  - Contrib: contrib.md
  - Troubleshooting: troubleshooting.md
  - Testing: testing.md
  - Settings: settings.md
  - Base classes: base.md
  - Credits: credits.md
