site_name: django-pgschemas
theme:
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
nav:
  - Overview: index.md
  - Usage: basic.md
  - Advanced: advanced.md
  - Troubleshooting: troubleshooting.md
  - Settings: settings.md
  - Credits: credits.md
